# Generated by Django 6.0.3 on 2026-03-13 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_date', models.DateTimeField()),
                ('event_start_time', models.DateTimeField()),
                ('event_end_time', models.DateTimeField()),
                ('event_seats', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='event_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='events.category')),
            ],
        ),
    ]
