# Generated by Django 6.0.3 on 2026-03-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Category',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/ '),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category'),
        ),
    ]
